name: mesma
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  
  - pip:
      - spectral-libraries 
      - mesma
      - ipykernel
      - jupyter_contrib_nbextensions 
  
  - requests 
  - chardet 
  - numpy 
  - gdal
  - boto3 
  - qgis==3.30

