name: Sentinel-2 Images Preprocessing

on:
  workflow_dispatch:
    inputs:
      s3_bucket:
        description: 'Input S3 bucket (eg: sce.sentinel2)'
        required: true
      s3_input_folder:
        description: 'Input S3 folder (eg: 2024_input_dir)'
        required: true
      s3_output_folder:
        description: 'Output S3 folder (eg: 2024_output_dir)'
        required: true

jobs:
  run-download:
    runs-on: ubuntu-latest
    steps:
      - name: Run preprocessing stage on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Starting stage: Download Sentinel-2 Images"
          
            # Check if EC2 Host is set (optional validation)
            if [ -z "${{ secrets.EC2_HOST }}" ]; then
              echo "::error::EC2_HOST is missing!"
              exit 1
            else
              echo "::notice::EC2_HOST is set"
            fi
            
            # Now actually run docker command with input arguments
            #docker pull dakshasinghal1999/download_image  # optional: pull latest image
            
            sudo docker run preprocessing_image \
              --s3_bucket "${{ github.event.inputs.s3_bucket }}" \
              --s3_input_folder "${{ github.event.inputs.s3_input_folder }}"
              --s3__output_folder "${{ github.event.inputs.s3__output_folder }}"

            echo "::notice::Download stage completed!"
      - name: Clean up stopped containers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Cleaning up stopped Docker containers"
            sudo docker rm -f $(sudo docker ps -aq)
