name: Generate Mesma Images

on:
  workflow_dispatch:
    inputs:
      s3_bucket:
        description: 'Output S3 bucket (eg: sce.sentinel2)'
        required: true
      s3_output_folder:
        description: 'Output S3 folder (eg: 2024_output_dir)'
        required: true
      image_files:
        description: 'comma separated files - No spaces (eg: 10_S_EG_2024_10_10.tif,10_S_EG_2024_11_10.tif)'
        required: true

jobs:
  run-mesma:
    runs-on: ubuntu-latest
    steps:
      - name: Run mesma stage on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Starting stage: Generate Mesma Images"
          
            # Check if EC2 Host is set (optional validation)
            if [ -z "${{ secrets.EC2_HOST }}" ]; then
              echo "::error::EC2_HOST is missing!"
              exit 1
            else
              echo "::notice::EC2_HOST is set"
            fi
            
            # Now actually run docker command with input arguments
            #docker pull dakshasinghal1999/mesma_image  # optional: pull latest image
            
            sudo docker run mesma_image \
              --image_files "${{ github.event.inputs.image_files }}" \
              --s3_bucket "${{ github.event.inputs.s3_bucket }}" \
              --s3_output_folder "${{ github.event.inputs.s3_output_folder }}"

            echo "::notice::Download stage completed!"
      - name: Clean up stopped containers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Cleaning up stopped Docker containers"
            sudo docker rm -f $(sudo docker ps -aq)
